# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'efirst3' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for efirst3
  pod 'GoogleSignIn', '~> 4.4.0'


  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
